tools:
  - class_name: verl.tools.mcp_base_tool.MCPBaseTool
    config:
      rate_limit: 120
      timeout: 120
      type: mcp
    mcp:
      mcp_servers_config_path: /workspace/verl/verl/examples/sglang_multiturn/config/tool_config/mcp_server.json
